In [1]:
# selenium
import selenium
import pandas as pd
from selenium import webdriver

# Beautiful soup
from bs4 import BeautifulSoup
import requests

import selenium
import pandas as pd
from selenium import webdriver
import warnings
warnings.filterwarnings('ignore')
from selenium.common.exceptions import StaleElementReferenceException,NoSuchElementException,ElementNotInteractableException
from selenium.webdriver.common.by import By
from time import sleep

# Q.1.

In [3]:
driver=webdriver.Chrome(r"C:\Users\Swati\Downloads\chromedriver_win32 (1)\chromedriver.exe")

In [4]:
url = 'https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos'
driver.get(url)

In [5]:
Rank = []
Name = []
Artist = []
Date = []
Views = []

In [14]:
# scraping Rank of the videos
try:
    for i in driver.find_elements(By.XPATH,"//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[1]"):
        Rank.append(i.text)
except NoSuchElementException:
    Rank.append("-")
        
# Scraping Name of the videos
try:
    for i in driver.find_elements(By.XPATH,"//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[2]"):
        Name.append(i.text)
except NoSuchElementException:
    Name.append("-")
        
# Scraping Artist of the videos
try:
    for i in driver.find_elements(By.XPATH,"//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[3]"):
        Artist.append(i.text)
except NoSuchElementException:
    Artist.append("-")
        
# Scraping Upload_Date of the videos
try:
    for i in driver.find_elements(By.XPATH,"//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[5]"):
        Date.append(i.text)
except NoSuchElementException:
    Date.append("-")
        
# Scraping Views of the videos
try:
    for i in driver.find_elements(By.XPATH,"//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[4]"):
        Views.append(i.text)
except NoSuchElementException:
    Views.append("-")
        
# creating DataFrame for scraped data
Wiki = pd.DataFrame({})
Wiki['Rank'] = Rank
Wiki['Name'] = Name
Wiki['Artist'] = Artist
Wiki['Upload Date'] = Date
Wiki['Views (in Billions)'] = Views

# removing stray numbers from Name column
Wiki.Name = Wiki.Name.apply(lambda x:x[:-4].strip('"'))
Wiki

,Rank,Name,Artist,Upload Date,Views (in Billions)
0,1.,Baby Shark Dance,Pinkfong Baby Shark - Kids' Songs & Stories,"June 17, 2016",11.40
1,2.,Despacito,Luis Fonsi,"January 12, 2017",7.98
2,3.,Johny Johny Yes Papa,LooLoo Kids,"October 8, 2016",6.47
3,4.,Shape of You,Ed Sheeran,"January 30, 2017",5.81
4,5.,See You Again,Wiz Khalifa,"April 6, 2015",5.64
5,6.,Bath Song,Cocomelon – Nursery Rhymes,"May 2, 2018",5.63
6,7.,Phonics Song with Two Words,ChuChu TV,"March 6, 2014",4.90
7,8.,Uptown Funk,Mark Ronson,"November 19, 2014",4.70
8,9.,Learning Colors – Colorful Eggs on a Farm,Miroshka TV,"February 27, 2018",4.65
9,10.,Gangnam Style,Psy,"July 15, 2012",4.55
10,11.,Masha and the Bear – Recipe for Disaster,Get Movies,"January 31, 2012",4.51
11,12.,Wheels on the Bus,Cocomelon – Nursery Rhymes,"May 24, 2018",4.40
12,13.,Dame Tu Cosita,El Chombo,"April 5, 2018",4.07
13,14.,Sugar,Maroon 5,"January 14, 2015",3.76
14,15.,Roar,Katy Perry,"September 5, 2013",3.66
15,16.,Counting Stars,OneRepublic,"May 31, 2013",3.65
16,17.,Sorry,Justin Bieber,"October 22, 2015",3.59
17,18.,Axel F,Crazy Frog,"June 16, 2009",3.52
18,18.,Thinking Out Loud,Ed Sheeran,"October 7, 2014",3.50
19,20.,Baa Baa Black Sheep,Cocomelon – Nursery Rhymes,"June 25, 2018",3.38
20,21.,Dark Horse,Katy Perry,"February 20, 2014",3.35
21,22.,Faded,Alan Walker,"December 3, 2015",3.34
22,23.,Girls Like You,Maroon 5,"May 31, 2018",3.33
23,24.,Let Her Go,Passenger,"July 25, 2012",3.30
24,25.,Bailando,Enrique Iglesias,"April 11, 2014",3.27
25,26.,Lean On,Major Lazer,"March 22, 2015",3.26
26,27.,Perfect,Ed Sheeran,"November 9, 2017",3.26
27,28.,Waka Waka (This Time for Africa),Shakira,"June 4, 2010",3.25
28,29.,Shake It Off,Taylor Swift,"August 18, 2014",3.21
29,30.,Humpty the train on a fruits ride,Kiddiestv Hindi – Nursery Rhymes & Kids Songs,"January 26, 2018",3.17

# Q.2.

In [26]:
driver = webdriver.Chrome(r"C:\Users\Swati\OneDrive\Desktop\DataScience\chromedriver.exe")

In [27]:
url=('https://www.bcci.tv/')
driver.get(url)
sleep(2)

In [28]:
btn=driver.find_element(By.XPATH,'/html/body/nav/div[1]/div[2]/ul[1]/li[2]/a').click()
sleep(3)

# creating empty lists for scraping the data
Match = []
Series = []
Place = []
Date = []
Time = []

In [29]:
match = driver.find_elements(By.XPATH,"//div[@class='fixture__format-strip']/span[@class='u-unskewed-text fixture__format']")
for i in match:
    Match.append(i.text)

sleep(2)
series = driver.find_elements(By.XPATH,"//div[@class='fixture__format-strip']/span[@class='u-unskewed-text fixture__tournament-label u-truncated']")
for i in series:
    Series.append(i.text)
sleep(2)
    
place = driver.find_elements(By.XPATH,"//div[@class='fixture__description u-unskewed-text']/p/span")
for i in place:
    Place.append(i.text)
sleep(2)
    
date = driver.find_elements(By.XPATH,"//span[@class='fixture__datetime tablet-only']/strong[1]")
for i in date:
    Date.append(i.text)
sleep(2)
    
date=[i.split(' ',3)[:3] for i in Date]
date=[' '.join(i) for i in date]
Time=[i.split(' ',3)[-1] for i in Date]
sleep(2)

In [12]:
len(Match)

0

In [30]:
# creating data frame
fixture=pd.DataFrame({'Match Title': Match,
                          "Series": Series,
                          "Place": Place,
                          "Date": date,
                          "Time": Time})
fixture

Empty DataFrame
Columns: [Match Title, Series, Place, Date, Time]
Index: []

# Q.3.

In [35]:
driver = webdriver.Chrome(r"C:\Users\Swati\OneDrive\Desktop\DataScience\chromedriver.exe")

In [36]:
url = ("https://www.guru99.com/")
driver.get(url)
sleep(2)

In [37]:
Name = []
Description = []

In [38]:
# clicking on Selenium button
driver.find_element(By.XPATH,"//li//a[@title='Selenium']").click()
sleep(1)

# clicking on Exception Handling button
driver.find_element(By.XPATH,'//a[@title="Selenium Exception Handling (Common Exceptions List)"]').click()
sleep(1)

# scraping Name
for i in driver.find_elements(By.XPATH,"//table[@class='table table-striped']/tbody/tr/td[1]"):
    Name.append(i.text)
sleep(1)
    
# scraping Description
for i in driver.find_elements(By.XPATH,"//table[@class='table table-striped']/tbody/tr/td[2]"):
    Description.append(i.text)
sleep(1)

    
# creating the dataframe from the scraped data
Selenium = pd.DataFrame({})
Selenium['Exception_Name'] = Name
Selenium['Description'] = Description
Selenium

Empty DataFrame
Columns: [Exception_Name, Description]
Index: []

# Q.4.

In [44]:
driver = webdriver.Chrome(r"C:\Users\Swati\OneDrive\Desktop\DataScience\chromedriver.exe")

In [45]:
url = ("https://statisticstimes.com/")
driver.get(url)

In [48]:
# clicking on Economy button
driver.find_element(By.CLASS_NAME,'dropbtn').click()

In [52]:

# clicking on India
ind_search = driver.find_element(By.XPATH,'/html/body/div[2]/div[1]/div[2]/div[2]/div/a[3]')

india = ind_search.get_attribute("href")
driver.get(india)
sleep(3)

In [53]:
# clicking on GDP of Indian Economy
try:
    GDP = driver.find_element(By.XPATH,'//a[class="ec"]').click()
    sleep(3)
except NoSuchElementException:
    GDP_capita = driver.find_element(By.XPATH,'/html/body/div[2]/div[2]/div[2]/ul/li[2]/a').click()

In [54]:
Rank = []
State = []
GSDP1 = []
GSDP2 = []
Share = []
GDP_billion = []

# scraping Rank
try:
    for i in driver.find_elements(By.XPATH,"//table[@class='display dataTable']/tbody/tr/td[1]"):
        Rank.append(i.text)
except NoSuchElementException:
    Rank.append("_")
    
# scraping State
try:
    for i in driver.find_elements(By.XPATH,"//table[@class='display dataTable']/tbody/tr/td[2]"):
        State.append(i.text)
except NoSuchElementException:
    State.append("_")
    
# scraping GSDP at current price (19-20)
try:
    for i in driver.find_elements(By.XPATH,"//table[@class='display dataTable']/tbody/tr/td[3]"):
        GSDP1.append(i.text)
except NoSuchElementException:
    GSDP1.append("_")
    
# scraping GSDP at current price (18-19)
try:
    for i in driver.find_elements(By.XPATH,"//table[@class='display dataTable']/tbody/tr/td[4]"):
        GSDP2.append(i.text)
except NoSuchElementException:
    GSDP2.append("_")
    
# scraping Share (18-19)
try:
    for i in driver.find_elements(By.XPATH,"//table[@class='display dataTable']/tbody/tr/td[5]"):
        Share.append(i.text)
except NoSuchElementException:
    Share.append("_")
    
# scraping GDP $ billion
try:
    for i in driver.find_elements(By.XPATH,"//table[@class='display dataTable']/tbody/tr/td[6]"):
        GDP_billion.append(i.text)
except NoSuchElementException:
    GDP_billion.append("_")
    
    
# creating DataFrame from the scraped data
GDP = pd.DataFrame({})
GDP['Rank'] = Rank
GDP['State'] = State
GDP['GSDP at current price (19-20)'] = GSDP1
GDP['GSDP at current price (18-19)'] = GSDP2
GDP['Share (18-19)'] = Share
GDP['GDP($ billion)'] = GDP_billion
GDP

,Rank,State,GSDP at current price (19-20),GSDP at current price (18-19),Share (18-19),GDP($ billion)
0,1,Goa,"520,030","476,370",335%,"7,029"
1,2,Sikkim,"487,201","435,199",306%,"6,421"
2,3,Delhi,"427,309","394,216",277%,"5,817"
3,4,Chandigarh,-,"359,030",252%,"5,297"
4,5,Haryana,"290,712","260,287",183%,"3,840"
...,...,...,...,...,...,...
61,29,Manipur,"84,746","75,229",59.76%,"53,930"
62,30,Jharkhand,"79,873","73,155",58.11%,"57,863"
63,31,Uttar Pradesh,"65,704","62,652",49.77%,"44,618"
64,32,Bihar,"46,664","40,982",32.56%,"31,287"
65,33,Andaman & Nicobar Islands,-,-,-,-

# Q.5.

In [55]:
driver = webdriver.Chrome(r"C:\Users\Swati\OneDrive\Desktop\DataScience\chromedriver.exe")

In [56]:
url = ("https://github.com/")
driver.get(url)

In [18]:
# getting explore button and clicking on it
source = driver.find_element(By.XPATH,'/html/body/div[1]/header/div/div[2]/div/nav/ul/li[3]/button').click()

In [19]:
# selecting trending option
trend_url = driver.find_element(By.XPATH,"/html/body/div[1]/header/div/div[2]/div/nav/ul/li[3]/div/ul[3]/li[3]/a")
urls = trend_url.get_attribute("href")
driver.get(urls)

In [27]:
# creating empty list
URLs = []
repository_title = []
Description = []
Contributors = []
Language = []
lang = []

# fetching urls for each repository
repository = driver.find_elements(By.XPATH,"//h1[@class='h3 lh-condensed']//a")
for i in repository:
    URLs.append(i.get_attribute("href"))
    
# scraping Repository title data
title = driver.find_elements(By.XPATH,"//h1[@class = 'h3 lh-condensed']")
for i in title:
    repository_title.append(i.text)
    
# scraping data from all repository page
for i in URLs:
    driver.get(i)
    time.sleep(5)
    
    # scraping Repository Description data 
    try:
        desc = driver.find_element(By.XPATH,"//p[@class='f4 mt-3']")
        Description.append(desc.text)
    except NoSuchElementException:
        Description.append('-')
        
        
    # scraping Contributors Count data
    try:
        contributor = driver.find_element(By.XPATH,"//*[contains(text(),'    Contributors ')]")
        Contributors.append(contributor.text.replace('Contributors',''))
    except NoSuchElementException:
        Contributors.append('-')
    
    
    # scraping Languages used data
    try:
        for i in driver.find_elements(By.XPATH,"//ul[@class= 'list-style-none']//li//span[1]"):
            lang.append(i.text)
        Language.append(lang)
    except NoSuchElementException:
        Language.append('-')
        
        
# Data Framing
Github = pd.DataFrame({})
Github['Repository Title'] = repository_title
Github['Repository Description'] = Description
Github['Contributors Count'] = Contributors
Github['Language Used'] = Language
Github

,Repository Title,Repository Description,Contributors Count,Language Used
0,lkwq007 / stablediffusion-infinity,-,3,"[Python, HTML, JavaScript, Jupyter Notebook, S..."
1,TheAlgorithms / C-Plus-Plus,-,280,"[Python, HTML, JavaScript, Jupyter Notebook, S..."
2,iced-rs / iced,-,125,"[Python, HTML, JavaScript, Jupyter Notebook, S..."
3,sherlock-project / sherlock,-,171,"[Python, HTML, JavaScript, Jupyter Notebook, S..."
4,freeCodeCamp / freeCodeCamp,-,"4,549","[Python, HTML, JavaScript, Jupyter Notebook, S..."
5,novuhq / novu,-,109,"[Python, HTML, JavaScript, Jupyter Notebook, S..."
6,github / docs,-,"1,456","[Python, HTML, JavaScript, Jupyter Notebook, S..."
7,AUTOMATIC1111 / stable-diffusion-webui,-,89,"[Python, HTML, JavaScript, Jupyter Notebook, S..."
8,firstcontributions / first-contributions,-,"3,557","[Python, HTML, JavaScript, Jupyter Notebook, S..."
9,midudev / hacktoberfest-2022,-,80,"[Python, HTML, JavaScript, Jupyter Notebook, S..."
10,CodeEditApp / CodeEdit,-,71,"[Python, HTML, JavaScript, Jupyter Notebook, S..."
11,ToolJet / ToolJet,-,214,"[Python, HTML, JavaScript, Jupyter Notebook, S..."
12,HavocFramework / Havoc,-,6,"[Python, HTML, JavaScript, Jupyter Notebook, S..."
13,stefanprodan / podinfo,-,35,"[Python, HTML, JavaScript, Jupyter Notebook, S..."
14,total-typescript / beginners-typescript-tutorial,-,12,"[Python, HTML, JavaScript, Jupyter Notebook, S..."
15,fineanmol / Hacktoberfest2022,-,775,"[Python, HTML, JavaScript, Jupyter Notebook, S..."
16,ossamamehmood / Hacktoberfest2022,-,452,"[Python, HTML, JavaScript, Jupyter Notebook, S..."
17,Aashu-Dubey / React-Native-UI-Templates,-,-,"[Python, HTML, JavaScript, Jupyter Notebook, S..."
18,yt-dlp / yt-dlp,-,"1,023","[Python, HTML, JavaScript, Jupyter Notebook, S..."
19,TryGhost / Ghost,-,413,"[Python, HTML, JavaScript, Jupyter Notebook, S..."
20,mikeroyal / Steam-Deck-Guide,-,8,"[Python, HTML, JavaScript, Jupyter Notebook, S..."
21,developedbyed / react-portofolio-with-tailwind,-,-,"[Python, HTML, JavaScript, Jupyter Notebook, S..."
22,TheAlgorithms / Python,-,842,"[Python, HTML, JavaScript, Jupyter Notebook, S..."
23,GoVanguard / Getting-into-InfoSec-and-Cybersec...,-,5,"[Python, HTML, JavaScript, Jupyter Notebook, S..."
24,freqtrade / freqtrade,-,239,"[Python, HTML, JavaScript, Jupyter Notebook, S..."

# Q.6.

In [58]:
url = ("https://www.billboard.com/")
driver.get(url)
sleep(1)

In [60]:
charts=driver.find_element(By.XPATH,'/html/body/div[3]/header/div/div[2]/div/div/div[2]/div[2]/div/div/nav/ul/li[1]/a').click()

In [63]:
Song_Name = []
Artist_Name =[]
Last_week_rank = []
Peak_rank = []
Weeks_on_board = []

# getting urls for top 100 songs
urls = driver.find_element(By.XPATH,"/html/body/div[4]/header/div/div[3]/div/nav/ul/li[1]/a")
page_url = urls.get_attribute("href")
driver.get(page_url)
sleep(4)

# scraping data of song names
for i in driver.find_elements(By.XPATH,"//span[@class='chart-element__information__song text--truncate color--primary']"):
    Song_Name.append(i.text)
    
# scraping data of artist names
for i in driver.find_elements(By.XPATH,"//span[@class='chart-element__information__artist text--truncate color--secondary']"):
    Artist_Name.append(i.text)
    
# scraping data of last week ranks
for i in driver.find_elements(By.XPATH,"//div[@class='chart-element__meta text--center color--secondary text--last']"):
    Last_week_rank.append(i.text)
    

# scraping data of peak ranks
for i in driver.find_elements(By.XPATH,"//div[@class='chart-element__meta text--center color--secondary text--peak']"):
    Peak_rank.append(i.text)       
    
    
# scraping data of weeks on board
for i in driver.find_elements(By.XPATH,"//div[@class='chart-element__meta text--center color--secondary text--week']"):
    Weeks_on_board.append(i.text)
    
    
# creating dataframe for scraped data
billiboard = pd.DataFrame({})
billiboard['Name'] = Song_Name
billiboard['Artist'] = Artist_Name
billiboard['Last Week Rank'] = Last_week_rank
billiboard['Peak Rank'] = Peak_rank
billiboard['Weeks on board'] = Weeks_on_board
billiboard

Empty DataFrame
Columns: [Name, Artist, Last Week Rank, Peak Rank, Weeks on board]
Index: []

# Q.7.

In [64]:
driver = webdriver.Chrome(r"C:\Users\Swati\OneDrive\Desktop\DataScience\chromedriver.exe")

In [65]:
url = ("https://www.naukri.com/")
driver.get(url)
sleep(3)

In [66]:
try:
    recruter = driver.find_element(By.XPATH,'//a[class="ec"]').click()
    
except NoSuchElementException:
     companies= driver.find_element(By.XPATH,'/html/body/div[1]/div[4]/div[2]/nav/ul/li[2]/a').click()

In [67]:
search = driver.find_element(By.XPATH,'//span[@class="nI-gNb-sb__placeholder"]').send_keys('Data Science')

ElementNotInteractableException: Message: element not interactable
  (Session info: chrome=106.0.5249.62)
Stacktrace:
Backtrace:
	Ordinal0 [0x002DDF13+2219795]
	Ordinal0 [0x00272841+1779777]
	Ordinal0 [0x00184100+803072]
	Ordinal0 [0x001AE523+976163]
	Ordinal0 [0x001ADB93+973715]
	Ordinal0 [0x001CE7FC+1107964]
	Ordinal0 [0x001A94B4+955572]
	Ordinal0 [0x001CEA14+1108500]
	Ordinal0 [0x001DF192+1175954]
	Ordinal0 [0x001CE616+1107478]
	Ordinal0 [0x001A7F89+950153]
	Ordinal0 [0x001A8F56+954198]
	GetHandleVerifier [0x005D2CB2+3040210]
	GetHandleVerifier [0x005C2BB4+2974420]
	GetHandleVerifier [0x00376A0A+565546]
	GetHandleVerifier [0x00375680+560544]
	Ordinal0 [0x00279A5C+1808988]
	Ordinal0 [0x0027E3A8+1827752]
	Ordinal0 [0x0027E495+1827989]
	Ordinal0 [0x002880A4+1867940]
	BaseThreadInitThunk [0x76536739+25]
	RtlGetFullPathName_UEx [0x77408FD2+1218]
	RtlGetFullPathName_UEx [0x77408F9D+1165]
	(No symbol) [0x00000000]

In [ ]:
btn = driver.find_element(By.XPATH,'//span[@class="ni-gnb-icn ni-gnb-icn-search"]').click()
time.sleep(3)

In [55]:
try :
    search.send_keys("Data Science")
    
except ElementNotInteractableException:
    pass
    search.send_keys("Data Scientist")

ElementNotInteractableException: Message: element not interactable
  (Session info: chrome=106.0.5249.62)
Stacktrace:
Backtrace:
	Ordinal0 [0x011BDF13+2219795]
	Ordinal0 [0x01152841+1779777]
	Ordinal0 [0x01064100+803072]
	Ordinal0 [0x0108E523+976163]
	Ordinal0 [0x0108DB93+973715]
	Ordinal0 [0x010AE7FC+1107964]
	Ordinal0 [0x010894B4+955572]
	Ordinal0 [0x010AEA14+1108500]
	Ordinal0 [0x010BF192+1175954]
	Ordinal0 [0x010AE616+1107478]
	Ordinal0 [0x01087F89+950153]
	Ordinal0 [0x01088F56+954198]
	GetHandleVerifier [0x014B2CB2+3040210]
	GetHandleVerifier [0x014A2BB4+2974420]
	GetHandleVerifier [0x01256A0A+565546]
	GetHandleVerifier [0x01255680+560544]
	Ordinal0 [0x01159A5C+1808988]
	Ordinal0 [0x0115E3A8+1827752]
	Ordinal0 [0x0115E495+1827989]
	Ordinal0 [0x011680A4+1867940]
	BaseThreadInitThunk [0x76536739+25]
	RtlGetFullPathName_UEx [0x77408FD2+1218]
	RtlGetFullPathName_UEx [0x77408F9D+1165]

# Q.8.

In [59]:
driver = webdriver.Chrome(r"C:\Users\Swati\OneDrive\Desktop\DataScience\chromedriver.exe")

In [60]:
url = ("https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare/")
driver.get(url)
time.sleep(3)

In [62]:
# creating empty lists
Book_name = []
Author_name = []
Volumes_sold = []
Publisher = []
Genre = []


# scraping book names data
for i in driver.find_elements(By.XPATH,"//tbody//tr//td[2]"):
    Book_name.append(i.text)

    
# scraping author names data
for i in driver.find_elements(By.XPATH,"//tbody//tr//td[3]"):
    try:
        if i.text == '0' : raise NoSuchElementException
        Author_name.append(i.text)
    except NoSuchElementException:
        Author_name.append('-')
time.sleep(3)


# scraping data of volumes sold
for i in driver.find_elements(By.XPATH,"//tbody//tr//td[4]"):
    Volumes_sold.append(i.text)
    
    
# scraping data of publisher names
for i in driver.find_elements(By.XPATH,"//tbody//tr//td[5]"):
    Publisher.append(i.text)
    
    
# scraping  data of genre
for i in driver.find_elements(By.XPATH,"//tbody//tr//td[6]"):
    Genre.append(i.text)    
    
    
# creating dataframe for scraped data
Novels = pd.DataFrame({})
Novels['Book Name'] = Book_name
Novels['Author'] = Author_name
Novels['Volume sold'] = Volumes_sold
Novels['Publisher'] = Publisher
Novels['Genre'] = Genre
Novels

,Book Name,Author,Volume sold,Publisher,Genre
0,"Da Vinci Code,The","Brown, Dan","5,094,805",Transworld,"Crime, Thriller & Adventure"
1,Harry Potter and the Deathly Hallows,"Rowling, J.K.","4,475,152",Bloomsbury,Children's Fiction
2,Harry Potter and the Philosopher's Stone,"Rowling, J.K.","4,200,654",Bloomsbury,Children's Fiction
3,Harry Potter and the Order of the Phoenix,"Rowling, J.K.","4,179,479",Bloomsbury,Children's Fiction
4,Fifty Shades of Grey,"James, E. L.","3,758,936",Random House,Romance & Sagas
...,...,...,...,...,...
95,"Ghost,The","Harris, Robert","807,311",Random House,General & Literary Fiction
96,Happy Days with the Naked Chef,"Oliver, Jamie","794,201",Penguin,Food & Drink: General
97,"Hunger Games,The:Hunger Games Trilogy","Collins, Suzanne","792,187",Scholastic Ltd.,Young Adult Fiction
98,"Lost Boy,The:A Foster Child's Search for the L...","Pelzer, Dave","791,507",Orion,Biography: General
99,Jamie's Ministry of Food:Anyone Can Learn to C...,"Oliver, Jamie","791,095",Penguin,Food & Drink: General

# Q.9.

In [68]:
driver = webdriver.Chrome(r"C:\Users\Swati\OneDrive\Desktop\DataScience\chromedriver.exe")

In [69]:
url = ("https://www.imdb.com/list/ls095964455/")
driver.get(url)

In [70]:
Name = []
Year_span = []
Genre = []
Run_time = []
Ratings = []
Votes = []

# scraped data of Names
for i in driver.find_elements(By.XPATH,"//h3[@class='lister-item-header']/a"):
    Name.append(i.text)
    
    
# scraped data of Year span
for i in driver.find_elements(By.XPATH,"//span[@class='lister-item-year text-muted unbold']"):
    Year_span.append(i.text)
    
    
# scraped data of Genre
for i in driver.find_elements(By.XPATH,"//span[@class='genre']"):
    Genre.append(i.text)
    
    
# scraped data of Run time
for i in driver.find_elements(By.XPATH,"//span[@class='runtime']"):
    Run_time.append(i.text)
    
    
# scraped data of Ratings
for i in driver.find_elements(By.XPATH,"//div[@class='ipl-rating-star small']//span[2]"):
    Ratings.append(i.text)
    
    
# scraped data of Votes
for i in driver.find_elements(By.XPATH,"//div[@class='lister-item-content']//p[4]/span[2]"):
    Votes.append(i.text) 
    
    
# creating dataframe for scraped data
TV_Series = pd.DataFrame({})
TV_Series['Name'] = Name
TV_Series['Year Span'] = Year_span
TV_Series['Genre'] = Genre
TV_Series['Run Time'] = Run_time
TV_Series['Ratings'] = Ratings
TV_Series['Votes'] = Votes
TV_Series

,Name,Year Span,Genre,Run Time,Ratings,Votes
0,Game of Thrones,(2011–2019),"Action, Adventure, Drama",57 min,9.2,"2,061,920"
1,Stranger Things,(2016– ),"Drama, Fantasy, Horror",51 min,8.7,"1,155,388"
2,The Walking Dead,(2010–2022),"Drama, Horror, Thriller",44 min,8.1,"972,544"
3,13 Reasons Why,(2017–2020),"Drama, Mystery, Thriller",60 min,7.5,"289,951"
4,The 100,(2014–2020),"Drama, Mystery, Sci-Fi",43 min,7.6,"249,371"
...,...,...,...,...,...,...
95,Reign,(2013–2017),Drama,42 min,7.4,"49,698"
96,A Series of Unfortunate Events,(2017–2019),"Adventure, Comedy, Drama",50 min,7.8,"60,759"
97,Criminal Minds,(2005–2020),"Crime, Drama, Mystery",42 min,8.1,"195,561"
98,Scream: The TV Series,(2015–2019),"Comedy, Crime, Drama",45 min,7.1,"41,159"
99,The Haunting of Hill House,(2018),"Drama, Horror, Mystery",572 min,8.6,"238,241"

# Q.10.

In [71]:
driver = webdriver.Chrome(r"C:\Users\Swati\OneDrive\Desktop\DataScience\chromedriver.exe")

In [72]:
url = (" https://archive.ics.uci.edu/")
driver.get(url)

In [73]:
viewall_dataset = driver.find_element(By.XPATH,"//tbody[1]//tr/td[2]/span[2]/a")
page_url = viewall_dataset.get_attribute("href")
driver.get(page_url)
sleep(3)

In [74]:
view_list = driver.find_element(By.XPATH,"/html/body/table[2]/tbody/tr/td[2]/table[1]/tbody/tr/td[2]/p/a")
list_url = view_list.get_attribute("href")
driver.get(list_url)
sleep(3)

In [75]:
dataset_url = driver.find_elements(By.XPATH,"//p[@class='normal']//b/a")

urls = []
for i in dataset_url:
    urls.append(i.get_attribute("href"))

In [77]:
# creating empty lists

Dataset_name = []
Data_type = []
Task = []
Attribute_type = []
No_of_instances = []
No_of_attributes = []
Year = []

for i in urls:
    driver.get(i)
    sleep(3)
    
    
    # scraping  Dataset name
    try:
        dataset_name = driver.find_element(By.XPATH,"//span[@class='heading']")
        Dataset_name.append(dataset_name.text)
    except NoSuchElementException:
        Dataset_name.append('-')
    sleep(3)
    
    
    
    # scraping data type
    try:
        data_type = driver.find_element(By.XPATH,"//table[@border='1']//tbody/tr/td[2]")
        if data_type.text == "N/A": raise NoSuchElementException
        Data_type.append(data_type.text)
    except NoSuchElementException:
        Data_type.append('-')
    sleep(3)
    
    
    # scraping Task
    try:
        task = driver.find_element(By.XPATH,"//table[@border='1']//tbody/tr[3]/td[2]")
        if task.text == "N/A": raise NoSuchElementException
        Task.append(task.text)
    except NoSuchElementException:
        Task.append('-')
    sleep(3)
    
    
    
    # scraping Attribute type
    try:
        attribute_type = driver.find_element(By.XPATH,"//table[@border='1']//tbody/tr[2]/td[2]")
        if attribute_type.text == "N/A": raise NoSuchElementException
        Attribute_type.append(attribute_type.text)
    except NoSuchElementException:
        Attribute_type.append('-')
    sleep(3)
    
    
    
    # scraping No of Instances
    try:
        instances = driver.find_element(By.XPATH,"//table[@border='1']//tbody/tr/td[4]")
        if instances.text == "N/A": raise NoSuchElementException
        No_of_instances.append(instances.text)
    except NoSuchElementException:
        No_of_instances.append('-')
    sleep(3)
    
    
    
    # scraping No of Arrtibutes
    try:
        attribute = driver.find_element(By.XPATH,"//table[@border='1']//tbody/tr[2]/td[4]")
        if attribute.text == "N/A": raise NoSuchElementException
        No_of_attributes.append(attribute.text)
    except NoSuchElementException:
        No_of_attributes.append('-')
    sleep(3)
    
    
    # scraping Year
    try:
        year = driver.find_element(By.XPATH,"//table[@border='1']//tbody/tr[2]/td[6]")
        if year.text == "N/A": raise NoSuchElementException
        Year.append(year.text[:4])
    except NoSuchElementException:
        Year.append('-')
    sleep(3)

In [81]:
# creating dataframe for scraped data
ML = pd.DataFrame({})
ML['Data_name'] = Dataset_name
ML['Data Type '] = Data_type
ML['Task '] = Task 
ML['Attribute Type '] = Attribute_type 
ML['No of Instance '] = No_of_instances
ML['No of Attributes '] = No_of_attributes 
ML['Year '] = Year 
ML

,Data_name,Data Type,Task,Attribute Type,No of Instance,No of Attributes,Year
0,2.4 GHZ Indoor Channel Measurements Data Set,Multivariate,Classification,Real,7840,5,2018
1,"3D Road Network (North Jutland, Denmark) Data Set","Sequential, Text","Regression, Clustering",Real,434874,4,2013
2,3W dataset Data Set,"Multivariate, Time-Series","Classification, Clustering","Integer, Real",1984,8,2019
3,9mers from cullpdb Data Set,Sequential,"Classification, Regression",Real,158716,4,2021
4,: Simulated Data set of Iraqi tourism places D...,Multivariate,"Classification, Clustering",-,232,16,2020
...,...,...,...,...,...,...,...
617,Youtube cookery channels viewers comments in H...,"Multivariate, Text",Classification,-,9800,3,2019
618,YouTube Multiview Video Games Dataset Data Set,"Multivariate, Text","Classification, Clustering","Integer, Real",120000,1000000,2013
619,YouTube Spam Collection Data Set,Text,Classification,-,1956,5,2017
620,Z-Alizadeh Sani Data Set,-,Classification,"Integer, Real",303,56,2017
621,Zoo Data Set,Multivariate,Classification,"Categorical, Integer",101,17,1990